# Generated by Django 5.0.4 on 2024-05-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productimage',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
