# Generated by Django 5.0.4 on 2024-05-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_alter_cart_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='productimage',
        ),
    ]
