# Generated by Django 5.0.4 on 2024-05-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, default='header_img.png', null=True, upload_to='static/'),
        ),
    ]
