# Generated by Django 5.0.4 on 2024-05-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_alter_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.AddField(
            model_name='cart',
            name='productimage',
            field=models.ImageField(blank=True, default='header_img.png', null=True, upload_to='static/'),
        ),
    ]
