# Generated by Django 5.0.4 on 2024-05-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('items', models.JSONField()),
                ('amount', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('status', models.CharField(default='Food Processing', max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('payment', models.BooleanField(default=False)),
            ],
        ),
    ]
