# Generated by Django 5.0.4 on 2024-05-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Food Processing', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
